version: '3.8'

services:
  chrome:
    build: .
    environment:
      - HEADLESS=true # Запуск браузера в фоновом режиме
    networks:
      - test-network

networks:
  test-network:
    driver: bridge