name: Java Playwright Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Установка Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # Кеширование зависимостей Maven
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Установка системных зависимостей для Playwright
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libgbm-dev x11-xkb-utils

      # Запуск Xvfb и тестов
      - name: Start virtual display
        run: |
          Xvfb :99 -screen 0 1280x720x24 &
          export DISPLAY=:99
          # Запускаем ffmpeg для записи экрана в WebM
          nohup ffmpeg -f x11grab -video_size 1280x720 -i :99.0+0,0 -r 25 -c:v libvpx -b:v 1M -pix_fmt yuv420p output.webm > ffmpeg.log 2>&1 &
          echo $! > ffmpeg_pid.txt

      - name: Run tests
        run: |
          mvn test -Dtest=CheckboxTest

      - name: Stop recording and save video
        run: |
          # Остановить ffmpeg по PID
          kill $(cat ffmpeg_pid.txt)
          # Подождать завершения процесса
          sleep 2

      # Проверка содержимого папки с видео
      - name: Check video directory
        run: |
          echo "Contents of videos directory:"
          ls -la videos/

      # Загрузка видео как артефактов
      - name: Upload videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: videos
          path: videos/